name: Rust 跨平台构建

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: GModPatchTool-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: GModPatchTool-windows
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: GModPatchTool-macos

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: 安装 Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          cache: true

      - name: 使用 Cargo 缓存加快速度
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: 缓存 Cargo 构建产物
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-${{ matrix.target }}-

      - name: 安装 cargo-chef
        run: cargo install cargo-chef --locked

      - name: 生成 cargo-chef 配方
        run: cargo chef prepare --recipe-path recipe.json --bin gmodpatchtool

      - name: 构建已缓存的依赖（cargo-chef）
        run: cargo chef cook --release --target ${{ matrix.target }} --recipe-path recipe.json

      - name: 构建发布二进制
        env:
          # 启用链接时优化（LTO）
          CARGO_PROFILE_RELEASE_LTO: "true"
          # 设置优化级别为最小大小
          CARGO_PROFILE_RELEASE_OPT_LEVEL: "z"
          # 禁用增量编译以获得更好的优化
          CARGO_PROFILE_RELEASE_INCREMENTAL: "false"
          # 设置代码生成单元为1
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: "1"
        run: cargo build --release --target ${{ matrix.target }}

      - name: 上传 workflow Artifact（Windows）
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/gmodpatchtool.exe

      - name: 上传 workflow Artifact（macOS/Linux）
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/gmodpatchtool

      - name: 上传发布文件（Windows）
        if: runner.os == 'Windows' && github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/gmodpatchtool.exe
          tag_name: ${{ github.ref }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传发布文件（macOS/Linux）
        if: runner.os != 'Windows' && github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/gmodpatchtool
          tag_name: ${{ github.ref }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}