name: 构建和发布

on:
  workflow_dispatch:
  push:
    branches: [ main, master, dev ]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: 在 ${{ matrix.os }} 上构建
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: gmodpatchtool.exe
            asset_name: gmodpatchtool-windows-x64.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: gmodpatchtool
            asset_name: gmodpatchtool-linux-x64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: gmodpatchtool
            asset_name: gmodpatchtool-macos-x64

    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: 设置Rust工具链
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: 缓存Cargo依赖
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: 安装系统依赖 (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-dev libwayland-dev libx11-dev libxcursor-dev libxrandr-dev libxi-dev libgl1-mesa-dev

      - name: 构建项目
        run: cargo build --release --target ${{ matrix.target }}

      - name: 准备构建产物
        shell: bash
        run: |
          mkdir -p artifacts
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} artifacts/${{ matrix.asset_name }}
          else
            cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} artifacts/${{ matrix.asset_name }}
            chmod +x artifacts/${{ matrix.asset_name }}
          fi

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: artifacts/${{ matrix.asset_name }}

  release:
    name: 创建发布
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 上传Windows发布资源
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/gmodpatchtool-windows-x64.exe/gmodpatchtool-windows-x64.exe
            artifacts/gmodpatchtool-linux-x64/gmodpatchtool-linux-x64
            artifacts/gmodpatchtool-macos-x64/gmodpatchtool-macos-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}